595 carousel
AUBGTheHUB/monolith pull request #600
Opened 2024-01-03 21:18 UTC by Pastedko

# Reference the ISSUE in the beggining of the title of the PR
e.g. #129 Created a new carousel (#595)

Created a new carousel for the main page

resolves #595 
> ^^^ the above will automatically append the issue to the PR and close it out when it's merged.

## How to verify:

- [ ] Open the main page

2024-04-22 10:36 UTC, Aleks1908 requested changes

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/test.css
If you are not using this remove this file.

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/members.old.css
Remove this

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/Carousel.jsx
Remove this

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/Carousel.old.old.jsx
Remove this

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/MembersCard.old.jsx
Remove this

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/MembersSection.old.jsx
Remove this

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/MobileCarousel.old.old.jsx
Remove this

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/Carousel.jsx
> +            return (
Rename all tedko classNames. lol

2024-04-22 10:36 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/MemberPage.jsx
> +                // let localMembers = [];
Remove comments

2024-04-23 11:16 UTC, Aleks1908 requested changes

2024-04-23 11:16 UTC, Aleks1908 commented on packages/web/src/components/spa/MembersSection/Carousel.jsx
> +    constructor(props) {
Avoid using jquery. Look at how you have implemented it in the HackAUBG page and do it in the same way here

2024-09-27 19:25 UTC, IvanObreshkov commented
@Pastedko @Aleks1908 will this PR get closed :D

2024-09-28 22:36 UTC, closed without merging

2024-09-28 22:36 UTC, asynchroza commented
> @Pastedko @Aleks1908 will this PR get closed :D

They've set up a new React project. These changes are not required anymore.