#828 implement About and Past Events Section
AUBGTheHUB/monolith pull request #830
Opened 2024-12-30 13:36 UTC by Isak-Bego

#828 implement About and Past Events Section

## Changed the tailwind config:
You could only set colors using the hsl representation of a color, which is not always the most convenient way. I only changed the ones I used. 

## Added a global css: 
This is mainly to declare color variables that you can use directly with tailwind. I set this colors on the context of the section, not on a global one, that is why they are defined inside the class of my section.

## Created resuable components for implementing the sections
## Found a cool library! Long Live Embla Carousel! 
It has pre-written examples, since the library is super light and you need to build the visual carousel on your own. It has amazing docs and is well-maintained. I am in love with how responsive and how little code it takes to acheive things. Amaaaazing!

resolves #828 

## How to verify:

- [ ] Navigate to my branch

- [ ] Start the Front End

- [ ] Compare with the Figma design

2025-01-01 15:17 UTC, Aleks1908 requested changes

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
> +const EventTicket: React.FC<PropType> = ({ imgSrc, title, tags }) => {
Lets stick with one way of defining types of functions. Remove the React.FC and put PropType after the definition of the variables and it should work

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
> +type PropType = {
Think of a more appropriate name

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
> +const EventTicket: React.FC<PropType> = ({ imgSrc, title, tags }) => {
Also lets export the component on this line instead of on the bottom

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +const IdentitySection: React.FC = () => {
You dont need React.FC here. And export it on this line

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +const PastEventSection: React.FC = () => {
You dont need React.FC here and export it here as well

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +    const SLIDES: React.ReactElement[] = pastEvents.map((pastEvent, index) => (
This is a constant that does not depend on any props and for the code to be more optimized extract it before the definiton of the component. This will make it not be redefined everytime there is change in this component

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +    const OPTIONS: EmblaOptionsType = { align: 'start', slidesToScroll: 'auto' };
This as well

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/MainPage.tsx
> +            <h1>MainPage</h1>
Remove this

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/MainPage.tsx
> +        <>
Use React Fragment when you want to have an empty tag

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <p className="font-hank mb-10">{identityProposition.message}</p>
I would say for readability this message should not be extracted in a different file. I get the idea for the other stuff because the plan is to have a lot of cards. But for this text i think its unnecessary

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +            <h1 className="font-semibold text-3xl text-primary mb-10">Our Past Events</h1>
Its not ok to have multiple h1s in one page. Use h2 instead

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <h1 className="font-mont font-semibold text-3xl text-primary mb-10">Who are we?</h1>
Its not ok to have multiple h1s in one page. Use h2 instead

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarousel.tsx
> +                <div className="embla__dots">
Rework this to be hidden when we have 1 page of cards

2025-01-01 15:17 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +        <div className="mb-40">
I looked at the design and i think the margin between the two components is less. And even if its not i dont like it currently lets lower it down a little bit what do you think?

2025-01-03 08:41 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <p className="font-hank mb-10">{identityProposition.message}</p>
I did the text this way so that we can change it later on through an admin panel, if we decide to change the identity proposition

2025-01-03 08:43 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +        <div className="mb-40">
Yeah we could lower it a little.

2025-01-05 16:38 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
> +const EventTicket: React.FC<PropType> = ({ imgSrc, title, tags }) => {
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:38 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
> +type PropType = {
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:38 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +const IdentitySection: React.FC = () => {
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:39 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +const PastEventSection: React.FC = () => {
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:39 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +    const SLIDES: React.ReactElement[] = pastEvents.map((pastEvent, index) => (
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:39 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +            <h1 className="font-semibold text-3xl text-primary mb-10">Our Past Events</h1>
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:39 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <h1 className="font-mont font-semibold text-3xl text-primary mb-10">Who are we?</h1>
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:40 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +        <div className="mb-40">
Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-05 16:41 UTC, Isak-Bego commented on services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarousel.tsx
> +                <div className="embla__dots">
Fixed in 625f48882926fac84c63f952574d016d6846d0fe

2025-01-05 17:59 UTC, asynchroza commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <p className="font-hank mb-10">{identityProposition.message}</p>
Not a good idea. Have this as a constant.

Changing this accordingly would take less than a minute if marketing demands it. 
By having it as a dynamic entry, you're introducing a point of failure.

2025-01-05 18:00 UTC, asynchroza commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <p className="font-hank mb-10">{identityProposition.message}</p>
The point of failure is not as much an issue as it would just be looking weird when the request is not yet resolved.

2025-01-05 18:02 UTC, asynchroza commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +    const SLIDES: React.ReactElement[] = pastEvents.map((pastEvent, index) => (
> This will make it not be redefined everytime there is change in this component

~~redefined~~ reinitialized

2025-01-05 18:02 UTC, asynchroza commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +const PastEventSection: React.FC = () => {
Having it as a default export is not an issue as long as it's consistent with other implementations.

2025-01-05 19:32 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <p className="font-hank mb-10">{identityProposition.message}</p>
That's a good reason @asynchroza

2025-01-05 19:39 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
> +            <p className="font-hank mb-10">{identityProposition.message}</p>
Fixed in aa40bf11a8b6a172a0040c397f6b39d9b23fe5e8

2025-01-06 00:08 UTC, Aleks1908 requested changes

2025-01-06 00:08 UTC, Aleks1908 commented on services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
> +export default function EventTicket({ imgSrc, title, tags }: { imgSrc: string; title: string; tags: Array<string> }) {
What i meant is to leave it a type but give it a better name. Make it for example "EventTicketType" and bring it back as it was before

2025-01-06 00:08 UTC, Aleks1908 commented on services/web/src/website/MainPage/MainPage.tsx
> +        <>
You havent addressed these

2025-01-06 00:08 UTC, Aleks1908 commented on services/web/src/website/MainPage/MainPage.tsx
> +            <h1>MainPage</h1>
You havent addressed these

2025-01-06 10:04 UTC, Isak-Bego commented on services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
> +    const OPTIONS: EmblaOptionsType = { align: 'start', slidesToScroll: 'auto' };
Fixed in Fixed in 59e824a8dd6bbfef341ccacaa12e1a8af24d5365

2025-01-06 10:14 UTC, Isak-Bego commented on services/web/src/website/MainPage/MainPage.tsx
> +            <h1>MainPage</h1>
Fixed in 0a2505d4f58a62a85131c703a5bcfeb4b394b04f

2025-01-06 10:14 UTC, Isak-Bego commented on services/web/src/website/MainPage/MainPage.tsx
> +        <>
Fixed in 0a2505d4f58a62a85131c703a5bcfeb4b394b04f

2025-01-06 18:20 UTC, Aleks1908 approved these changes
LGTM

2025-01-06 18:24 UTC, merged